name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
      - meimingweili
      - cipool041
      - mikey
      - placeholder3
  pull_request:
    branches:
      - main
      - meimingweili
      - cipool041
      - mikey
      - placeholder3


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubutu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: echo "Python has been successfully installed"

      - name: Cache Python dependencies
        run: |
          pip -m pip install --upgrade pip
          pip install pytest
          echo "Dependencies have been successfully installed"
      - name: Run tests
        run: pytest

